name: Publish to Azure Container Registry

on:
  push:
    branches:
      - 'conquest/master'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to Azure Container Registry
        uses: docker/login-action@v1 
        with:
          registry: devazurecontainerregistry.azurecr.io
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          registry: devazurecontainerregistry.azurecr.io
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            docus-proxy:latest
            docus-proxy:1.0.0